Teste
oushiro/teste_pullGit_texFiles pull request #2
Opened 2020-01-07 21:48 UTC by g-silveira

Testando pull request

2020-01-07 21:56 UTC, g-silveira commented on teste_pullGitHub.tex
Comentário teste 1

2020-01-07 21:56 UTC, g-silveira commented on teste_pullGitHub.tex
> +Testando pull request
comentário 2

2020-01-07 22:03 UTC, oushiro requested changes
Veja comentários abaixo:

2020-01-07 22:03 UTC, oushiro commented on teste_pullGitHub.tex
> +\documentclass[11pt,a4paper,oneside]{article}
De acordo com a mudança!

2020-01-07 22:03 UTC, oushiro commented on teste_pullGitHub.tex
ok!

2020-01-07 22:03 UTC, oushiro commented on teste_pullGitHub.tex
> +Etiam eget ligula eu lectus lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget ligula eu lectus lobortis condimentum. Aliquam nonummy auctor massa. Pellentes habitant morbi
Neste parágrafo, mantenha "auctor" em vez de "auctora". As demais mudanças estão ok.

2020-01-07 22:03 UTC, oushiro commented on teste_pullGitHub.tex
> +Testando pull request
ok!

2020-01-08 12:55 UTC, oushiro approved these changes

2020-01-08 12:55 UTC, merged